language: python

python:
    - 3.6

cache: pip

# install dependencies
before_script:
  - easy_install distribute
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
  - pip install coveralls

script:
    - pytest

after_success:
  - coveralls

