language: python

python:
    - 3.6

cache: pip

# install dependencies
before_script:
  - easy_install distribute
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

script:
  - python test_app.py
  - pytest --cov=YourModule/

after_success:
  - coveralls