language: python

python:
    - 3.6

cache: pip

# install dependencies
before_script:
  - easy_install distribute
  - pip install -r requirements.txt

script:
  - python test_app.py

after_success:
  - coveralls

